apiVersion: v1
kind: Service
metadata:
  name: notejar-service
  labels:
    app: notejar
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8507
    targetPort: 8507
    nodePort: 30001
  selector:
    app: notejar
    tier: frontend