apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: notejar
    tier: database
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: notejar
    tier: database